services:
  nginx:
    image: vlwli99/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - sseumsseumi-network

  frontend:
    image: vlwli99/frontend
    container_name: frontend
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - sseumsseumi-network
  
  backend:
    image: vlwli99/backend
    container_name: backend
    environment:
      - AWSRDS_PASSWORD=${AWSRDS_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - sseumsseumi-network
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/redis/data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - sseumsseumi-network

networks:
  sseumsseumi-network:
    driver: bridge